# .github/actions/security-scan/action.yml
name: 'Security Scan'
description: 'Run comprehensive security scans'

inputs:
  severity-level:
    description: 'Minimum severity level to report'
    required: false
    default: 'HIGH'
  fail-on-issues:
    description: 'Fail workflow if issues found'
    required: false
    default: 'true'

outputs:
  issues-found:
    description: 'Whether security issues were found'
    value: ${{ steps.scan.outputs.issues-found }}

runs:
  using: "composite"
  steps:
    - name: Run npm audit
      id: npm-audit
      shell: bash
      run: |
        npm audit --audit-level=${{ inputs.severity-level }} || echo "issues_found=true" >> $GITHUB_OUTPUT
        echo "issues-found=${{ steps.npm-audit.outputs.issues_found || 'false' }}" >> $GITHUB_OUTPUT

    - name: Run SAST scan
      shell: bash
      run: |
        # Example: Run semgrep or other SAST tools
        echo "Running SAST scan..."
        # Add your SAST tool commands here

    - name: Fail on issues
      if: inputs.fail-on-issues == 'true' && steps.npm-audit.outputs.issues_found == 'true'
      shell: bash
      run: exit 1
